### PR TITLE
upgrade nx-remotecache-custom to 4.2.1

### PR DESCRIPTION
**Pull request by pearsonradu**

### CODE REVIEW

**Comment by pearsonradu** [comment]
Bump @NiklasPor

**Comment by pearsonradu** [comment]
> Bump @NiklasPor

Bump @NiklasPor

**Comment by pearsonradu** [comment]
@NiklasPor is it possible to cut a release with this change? `4.2.1` says it contained this `unexpected end of file` fix but that is only included in the dependency upgrade from this PR.

**Comment by NiklasPor** [comment]
You actually don't need a release for that, the dependency from nx-remotecache-azure is prefixed with `^`, so it should automatically use it if you freshly resolve the dependency in your repository (that's how I tested that this is working at all). Depending on your package manager you might need to remove the lock file, or even the node_modules.

But yes, I can also create a new release.

**Comment by pearsonradu** [comment]
> You actually don't need a release for that, the dependency from nx-remotecache-azure is prefixed with `^`, so it should automatically use it if you freshly resolve the dependency in your repository (that's how I tested that this is working at all). Depending on your package manager you might need to remove the lock file, or even the node_modules.
> 
> But yes, I can also create a new release.

You're right. My lockfile is likely preventing those changes!

**Pull request merged**
