### PR TITLE
[Fix] Rename the prefix of environment variables

### PR DESCRIPTION
**Pull request by haven2world**
The previous ENV prefix `NX_` is the same as the pattern the nx react plugin used to inject environment variables into JS bundle. 
Doc: https://nx.dev/recipe/use-environment-variables-in-react#using-environment-variables-in-react-applications

So I prefer to rename the environment variables to avoid unexpected credential leak.

I failed to find a better name, so just use `NXCACHE_`
Any better idea?

### CODE REVIEW

**Comment by NiklasPor** [comment]
I'll brainstorm quickly and then apply the same change to all other nx-remotecache-* repos.

**Comment by kraiz** [comment]
I know naming things is hard, even more when it's related to caching [1]. Did you came up with a reasonable env prefix? I'm eager to use the package but can't if it leaks credentials...So this is just a friendly bump :)

[1] https://www.karlton.org/2017/12/naming-things-hard/

**Comment by NiklasPor** [comment]
Hey @kraiz , @haven2world  totally forgot about this. This MR looks good. 

I will:
* Merge this MR
* Update nx-remotecache-custom (base package)
* Update nx-remotecache-minio

And then create a new major release this weekend. Thanks for the reminder 👏

**Comment by NiklasPor** [comment]
3.0.0 should now require env variables in the `NXCACHE_` format

**Pull request merged**
