### PR TITLE
Use only BlockBlobClient

### PR DESCRIPTION
**Pull request by Sobuno**
Version 0.0.6 uses both BlobServiceClient, ContainerClient and BlockBlobClient. Using the connection string, I was not able to get the package to work when using a SAS token scoped to my particular container with only read and write access as it attempted to perform some unauthorized operations.

This PR simplifies the approach to only using a BlockBlobClient. I have verified that the ConnectionString approach works for my given scenario above whereas the account name+key approach is only based on the documentation in Azure's SDK

### CODE REVIEW

**Comment by NiklasPor** [comment]
Hey @Sobuno — thanks a lot for contributing! This PR looks good, but I need to test it locally before merging it.

I'll review & merge & release (if everything is fine) next week 🚀 (Currently not in range of a notebook)

**Comment by Sobuno** [comment]
Sounds good, @NiklasPor

**Comment by NiklasPor** [comment]
Tested it and works really well! Thanks for the contribution. I'll create a new release ASAP 🚀

**Comment by NiklasPor** [comment]
v0.0.7 includes your changes 👍 

image

**Pull request merged**
