### PR TITLE
feat: added azure active directory authentication

### PR DESCRIPTION
**Pull request by pearsonradu**
- Added `@azure/identity` package to authenticate with Active Directory (AD)
- Modifed `index.ts` to enable AD authentication via `NXCACHE_AZURE_AD_AUTH env var flag or `adAuth` attribute

### CODE REVIEW

**Comment by deadwards90** [comment]
@NiklasPor if I was to make this PR again but get it up to date with main, what are the chances of it getting merged? I'd love to be able to use this but the lack of Azure AD support is a bit of a blocker for me.

**Comment by NiklasPor** [comment]
Sorry, totally oversaw this one when I was upgrading nx-remotecache-custom yesterday. The PR looks fine, but could you describe to me how I can easily check if this is working on my local machine?

WIth these packages most of the work actually comes from verifying that they are working 😁

**Comment by pearsonradu** [comment]
> Sorry, totally oversaw this one when I was upgrading nx-remotecache-custom yesterday. The PR looks fine, but could you describe to me how I can easily check if this is working on my local machine?
> 
> WIth these packages most of the work actually comes from verifying that they are working 😁

Sorry, it has been a while since I wrote this and I'm trying to remember. I believe you can run `az login` locally and set `NXCACHE_AZURE_AD_AUTH` to `true`.

**Comment by pearsonradu** [comment]
Just bumping this PR since it got some attention last week

**Comment by pearsonradu** [comment]
> Just bumping this PR since it got some attention last week

Bump

**Comment by pearsonradu** [comment]
> > Just bumping this PR since it got some attention last week
> 
> Bump

Bump

**Comment by NiklasPor** [comment]
Thanks for your contribution, this will be part of the release which comes together with support for Nx 16.6 👍

**Comment by NiklasPor** [comment]
Thanks, the feature is available starting with `4.2.0` 👍

**Pull request merged**
