### PR TITLE
add container sas url parameter

### PR DESCRIPTION
**Pull request by kraiz**
Thanks for the package, it seems to work great. As I don't like to hand out the account key and provide complete access to the storage account, I added a SAS-based authentication option:
Much like with the ConnectionString you configure the SAS URL pointing to the blob container incl. SAS token (query string params) as single config option. Tools like Azure Storage Account Manager provide this URL via context menu of the container (permission "read + write" seems to be enough). 

It looks like this:

https://{accountName}.blob.core.windows.net/{containerName}?sv=2021-08-06&st=2022-11-18T19%3A11%3A26Z&se=2023-11-19T19%3A11%3A00Z&sr=c&sp=rwl&sig=7xhhp...E%3D

Maybe there's room for improvements on how to document it or rename the config options / env var.

### CODE REVIEW

**Comment by NiklasPor** [comment]
Awesome, I was thinking exactly this when I was setting up a storage again after some time to work with this package 👏

**Comment by GrumpyMeow** [comment]
Hi,
Having the option to use SAS would be great. This as now our developers have full access to a storage account. Which is undesired.

**Comment by NiklasPor** [comment]
I'll merge this and release a new version in the next 12 hours. Thanks for bumping!

**Comment by GrumpyMeow** [comment]
I'm trying the PR version of kraiz, but have yet to get things working. I receive the error: `Error: Unable to extract containerName with provided information.`.
Probably i'm using the wrong parameters.

**Comment by kraiz** [comment]
Sure, the PR assume you just set the SAS url and this url contains the container name as first path parameter. Have a look into the PR description above.

**Comment by GrumpyMeow** [comment]
Yep. Got it working.. I generated the SAS Url in the Azure Portal via the menu-item "Shared access signature". The displayed/given sas-url didn't work.
When i did it by using the "..." from the container, the generated SAS url does work.  
Thanks!

**Comment by NiklasPor** [comment]
Alright, the code looks good to me, plan and simple 👍  Thanks for the contribution!

**Comment by NiklasPor** [comment]
Changes available in `nx-remotecache-azure@3.1.0` 🚀

**Pull request merged**
